"""Approved, named constants used by the CFIE core unit engine."""

from backend.core.constants.unit_scales import (
    BASE_SCALE,
    GRAMS_PER_KILOGRAM,
    MICROGRAMS_PER_GRAM,
    MILLIGRAMS_PER_GRAM,
    MILLILITRES_PER_LITRE,
    MILLIMOLES_PER_MOLE,
    PARTS_PER_BILLION_PER_PERCENT_W_W,
    PARTS_PER_MILLION_PER_PERCENT_W_W,
    PARTS_PER_BILLION_PER_PART_PER_MILLION,
)

__all__ = [
    "BASE_SCALE",
    "GRAMS_PER_KILOGRAM",
    "MICROGRAMS_PER_GRAM",
    "MILLIGRAMS_PER_GRAM",
    "MILLILITRES_PER_LITRE",
    "MILLIMOLES_PER_MOLE",
    "PARTS_PER_BILLION_PER_PART_PER_MILLION",
    "PARTS_PER_BILLION_PER_PERCENT_W_W",
    "PARTS_PER_MILLION_PER_PERCENT_W_W",
]
